-- =========================================================
-- COHORT ANALYSIS: CUSTOMER BEHAVIOR & REVENUE TRENDS
-- =========================================================

-- Definition:
-- A cohort is a group of customers who share a common
-- characteristic — here, their FIRST purchase date.

-- Cohort Type:
-- Acquisition Cohort (based on first purchase)

-- Granularity:
-- 1. Yearly (macro trend analysis)
-- 2. Monthly (detailed behavioral analysis)

-- Key Objective:
-- Track how customer value evolves over time after acquisition.

-- =========================================================
-- WHY COHORT ANALYSIS?
-- =========================================================

-- 1. Identifies retention patterns over time
-- 2. Separates growth from customer acquisition vs engagement
-- 3. Removes noise from aggregate metrics
-- 4. Enables lifecycle-based decision making
-- 5. Helps evaluate marketing effectiveness by cohort


WITH customer_cohort AS
(
    SELECT
        customer_key,
        MIN(order_date_key) AS first_order_date_key
    FROM gold.fact_sales
    GROUP BY customer_key
)

SELECT
    d.order_fiscal_year AS cohort_fiscal_year,
    COUNT(*) AS total_customers
FROM customer_cohort c
JOIN gold.dim_order_date d
    ON c.first_order_date_key = d.order_date_key
GROUP BY
    d.order_fiscal_year
ORDER BY
    d.order_fiscal_year;

/*
cohort_fiscal_year	total_customers
NULL	            15
2011	            2199
2012	            3258
2013	            12506
2014	            506
*/
-- The null values are the results of invalid order dates in the source data.
-- =========================================================
-- STEP 3: COHORT REVENUE OVER TIME
-- =========================================================

-- Objective:
-- Track revenue generated by each cohort across years.

-- Key Concept:
-- year_offset = years since customer acquisition

-- Interpretation:
-- Y0 → Revenue in acquisition year
-- Y1 → Revenue 1 year after acquisition
-- ...

-- Use Case:
-- Evaluate long-term value and retention quality.
WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(d.order_date) AS first_order_date
    FROM gold.fact_sales f
    JOIN gold.dim_order_date d
        ON f.order_date_key = d.order_date_key
    GROUP BY f.customer_key
),
cohort_with_fiscal AS
(
    SELECT
        c.customer_key,
        c.first_order_date,
        d.order_fiscal_year AS cohort_fiscal_year
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date = d.order_date
),
cohort_activity AS
(
    SELECT
        c.customer_key,
        c.cohort_fiscal_year,
        c.first_order_date,
        d.order_date AS activity_date,
        s.sales_amount,

        FLOOR(DATEDIFF(DAY, c.first_order_date, d.order_date) / 365.0) AS year_offset

    FROM cohort_with_fiscal c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
)
SELECT
    cohort_fiscal_year,

    SUM(CASE WHEN year_offset = 0 THEN sales_amount ELSE 0 END) AS Y0,
    SUM(CASE WHEN year_offset = 1 THEN sales_amount ELSE 0 END) AS Y1,
    SUM(CASE WHEN year_offset = 2 THEN sales_amount ELSE 0 END) AS Y2,
    SUM(CASE WHEN year_offset = 3 THEN sales_amount ELSE 0 END) AS Y3,
    SUM(CASE WHEN year_offset = 4 THEN sales_amount ELSE 0 END) AS Y4

FROM cohort_activity
WHERE cohort_fiscal_year IS NOT NULL
GROUP BY cohort_fiscal_year
ORDER BY cohort_fiscal_year;
   
/*
cohort_fiscal_year	Y0	        Y1	        Y2	        Y3	    Y4
2011	            7053411	    2537374    	1817078	    0	    0
2012	            8449243	    3566232	    0	        0	    0
2013	            5901871	    0	        0	        0	    0
2014	            26049	    0	        0	        0	    0
*/
--_____________________________________________________________________YEAR 2013 - comparing customers according to the month they arrived_________________________________
-- =========================================================
-- STEP 4: MONTHLY COHORT ANALYSIS (YEAR = 2013)
-- =========================================================

-- Objective:
-- Break down cohorts by acquisition month for granular insights.

-- Output:
-- Number of customers acquired each month in 2013

-- Use Case:
-- Detect seasonality in acquisition (e.g., campaigns, holidays)
WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(f.order_date_key) AS first_order_date_key
    FROM gold.fact_sales f
    GROUP BY f.customer_key
)

SELECT
    d.order_fiscal_month_year AS cohort_period,
    COUNT(DISTINCT c.customer_key) AS total_customers
FROM customer_cohort c
JOIN gold.dim_order_date d
    ON c.first_order_date_key = d.order_date_key
WHERE d.order_fiscal_year = 2013
GROUP BY
    d.order_fiscal_month_year
ORDER BY
    d.order_fiscal_month_year;
/*
cohort_period	total_customers
Apr-2013      	1017
Aug-2013      	970
Dec-2013      	1285
Feb-2013      	1091
Jan-2013      	249
Jul-2013      	951
Jun-2013  	    1342
Mar-2013  	    1302
May-2013  	    1015
Nov-2013  	    1063
Oct-2013  	    1012
Sep-2013  	    1209
*/
-- =========================================================
-- STEP 4: MONTHLY COHORT ANALYSIS (YEAR = 2013)
-- =========================================================

-- Objective:
-- Break down cohorts by acquisition month for granular insights.

-- Output:
-- Number of customers acquired each month in 2013

-- Use Case:
-- Detect seasonality in acquisition (e.g., campaigns, holidays)
WITH customer_cohort AS (
    -- Identify the first purchase date per customer
    SELECT
        f.customer_key,
        MIN(d.order_date) AS first_order_date
    FROM gold.fact_sales f
    JOIN gold.dim_order_date d
        ON f.order_date_key = d.order_date_key
    GROUP BY f.customer_key
),
cohort_with_period AS (
    -- Map each customer to their cohort period string
    SELECT
        c.customer_key,
        c.first_order_date,
        d.order_fiscal_month_year AS cohort_period
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date = d.order_date
	WHERE d.order_fiscal_year = 2013
),
cohort_activity AS (
    -- Join all orders for these customers and calculate month offset
    SELECT
        c.customer_key,
        c.cohort_period,
        s.sales_amount,
        d.order_date AS activity_date,
        FLOOR(DATEDIFF(DAY, c.first_order_date, d.order_date) / 30.44) AS month_offset
    FROM cohort_with_period c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
)
SELECT
    cohort_period,
    SUM(CASE WHEN month_offset = 0 THEN sales_amount ELSE 0 END) AS M0,
    SUM(CASE WHEN month_offset = 1 THEN sales_amount ELSE 0 END) AS M1,
    SUM(CASE WHEN month_offset = 2 THEN sales_amount ELSE 0 END) AS M2,
    SUM(CASE WHEN month_offset = 3 THEN sales_amount ELSE 0 END) AS M3,
    SUM(CASE WHEN month_offset = 4 THEN sales_amount ELSE 0 END) AS M4,
    SUM(CASE WHEN month_offset = 5 THEN sales_amount ELSE 0 END) AS M5,
    SUM(CASE WHEN month_offset = 6 THEN sales_amount ELSE 0 END) AS M6,
    SUM(CASE WHEN month_offset = 7 THEN sales_amount ELSE 0 END) AS M7,
    SUM(CASE WHEN month_offset = 8 THEN sales_amount ELSE 0 END) AS M8,
    SUM(CASE WHEN month_offset = 9 THEN sales_amount ELSE 0 END) AS M9,
    SUM(CASE WHEN month_offset = 10 THEN sales_amount ELSE 0 END) AS M10,
    SUM(CASE WHEN month_offset = 11 THEN sales_amount ELSE 0 END) AS M11
FROM cohort_activity
GROUP BY cohort_period
ORDER BY MIN(activity_date);

/*
cohort_period	M0	        M1    	M2	        M3    	M4    	M5	    M6	    M7    	M8	    M9	    M10	     M11
Jan-2013  	    296217	    484	    596	        5617	3144	1126	5564	284    	1581	2256	4345	665
Feb-2013  	    297243	    4413	8808	    6108	9722	3872	3090	4456	4760	4441	3739	2204
Mar-2013  	    390165	    2156	2561	    12364	12197	9274	2810	2239	2784	2891	772    	0
Apr-2013  	    376308	    1662	7363	    6097	4297	2041	1566	1323	1619	1143	0	    0
May-2013  	    417302	    6457	8505	    11255	8468	1501	1357	1389	1406	0	    0    	0
Jun-2013  	    617676	    1509	7473	    15860	21714	2170	1584	677	    0	    0	    0    	0
Jul-2013  	    325660	    936    	1657	    1569	13543	11445	672    	0	    0	    0	    0    	0
Aug-2013  	    342637	    708    	3017	    6258	9374	622	    0	    0	    0	    0	    0    	0
Sep-2013  	    482736	    2956	1755	    1767	803	    0	    0	    0	    0	    0	    0    	0
Oct-2013  	    519960	    1452	1140	    516    	0	    0	    0	    0	    0	    0	    0    	0
Nov-2013      	692863	    1378	831	        0	    0	    0    	0	    0	    0	    0	    0    	0
Dec-2013  	    829904	    893	    149	        0	    0	    0	    0	    0	    0	    0	    0	    0
*/
-- =========================================================
-- STEP 5: MONTHLY REVENUE RETENTION MATRIX
-- =========================================================

-- Objective:
-- Track how each monthly cohort spends over time.

-- Key Metric:
-- month_offset = months since first purchase

-- Interpretation:
-- M0 → Revenue in acquisition month
-- M1 → Revenue next month
-- ...

-- Insight:
-- Helps visualize retention decay and repeat purchase behavior.

WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(f.order_date_key) AS first_order_date_key
    FROM gold.fact_sales f
    GROUP BY f.customer_key
),
cohort_base AS
(
    SELECT
        d.order_fiscal_year,
        d.order_fiscal_month,
        d.order_fiscal_month_year AS cohort_period,
        COUNT(DISTINCT c.customer_key) AS total_customers
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
    WHERE d.order_fiscal_year = 2013
    GROUP BY
        d.order_fiscal_year,
        d.order_fiscal_month,
        d.order_fiscal_month_year
),
cohort_with_date AS
(
    SELECT
        c.customer_key,
        d.order_fiscal_year,
        d.order_fiscal_month,
        d.order_fiscal_month_year AS cohort_period,
        d.order_date AS first_order_date
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
),
cohort_activity AS
(
    SELECT
        c.customer_key,
        c.cohort_period,
        c.order_fiscal_year AS cohort_year,
        c.order_fiscal_month AS cohort_month,
        d.order_fiscal_year AS activity_year,
        d.order_fiscal_month AS activity_month,
        s.sales_amount,

        -- Month offset using datediff in months
        DATEDIFF(MONTH, c.first_order_date, d.order_date) AS month_offset

    FROM cohort_with_date c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
    WHERE c.order_fiscal_year = 2013
)
SELECT
    a.cohort_period,
    b.total_customers,
    CAST(SUM(CASE WHEN month_offset = 0 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M0,
    CAST(SUM(CASE WHEN month_offset = 1 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M1,
    CAST(SUM(CASE WHEN month_offset = 2 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M2,
    CAST(SUM(CASE WHEN month_offset = 3 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M3,
    CAST(SUM(CASE WHEN month_offset = 4 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M4,
    CAST(SUM(CASE WHEN month_offset = 5 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M5,
    CAST(SUM(CASE WHEN month_offset = 6 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M6,
    CAST(SUM(CASE WHEN month_offset = 7 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M7,
    CAST(SUM(CASE WHEN month_offset = 8 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M8,
    CAST(SUM(CASE WHEN month_offset = 9 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M9,
    CAST(SUM(CASE WHEN month_offset = 10 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M10,
    CAST(SUM(CASE WHEN month_offset = 11 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M11

FROM cohort_activity a
JOIN cohort_base b
    ON a.cohort_period = b.cohort_period
GROUP BY
    a.cohort_period,
    b.total_customers
ORDER BY MIN(a.cohort_month);
/*
cohort_period	total_customers    	ARPU_M0	ARPU_M1	ARPU_M2	ARPU_M3	ARPU_M4	ARPU_M5	ARPU_M6	ARPU_M7	ARPU_M8	ARPU_M9	ARPU_M10	ARPU_M11
Jan-2013  	    249	                1187.31	2.32	2.00	22.04	12.80	2.82	4.38	22.35	1.14	6.38	24.60	2.37
Feb-2013  	    1091	        270.38	3.72	3.92	8.50	7.42	6.35	2.84	3.77	4.26	3.91	3.81	3.27
Mar-2013  	    1302	        298.09	2.35	2.17	5.31	11.65	6.95	3.58	2.11	2.10	1.96	1.69	0.15
Apr-2013  	    1017	        369.09	1.48	2.57	11.06	1.63	4.31	1.79	1.31	1.80	1.63	0.00	0.00
May-2013  	    1015	        410.29	2.13	8.40	13.08	10.76	1.22	1.65	1.49	1.86	0.00	0.00	0.00
Jun-2013  	    1342	        459.78	1.00	3.30	5.08	21.16	5.52	1.32	0.89	0.21	0.00	0.00	0.00
Jul-2013  	    951            	341.90	0.90	1.55	1.66	3.95	22.30	1.54	0.00	0.00	0.00	0.00	0.00
Aug-2013  	    970	            352.29	0.96	2.75	1.51	14.57	1.36	0.01	0.00	0.00	0.00	0.00	0.00
Sep-2013  	    1209	        396.40	1.63	2.33	1.65	1.14	0.13	0.00	0.00	0.00	0.00	0.00	0.00
Oct-2013  	    1012	        510.88	1.36	1.35	0.97	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
Nov-2013  	    1063	        651.43	1.23	1.07	0.14	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
Dec-2013  	    1285	        645.19	1.09	0.37	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
*/

WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(f.order_date_key) AS first_order_date_key
    FROM gold.fact_sales f
    GROUP BY f.customer_key
),
cohort_base AS
(
    SELECT
        d.order_fiscal_month_year AS cohort_period,
        d.order_fiscal_year,
        d.order_fiscal_month,
        COUNT(DISTINCT c.customer_key) AS total_customers
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
    WHERE d.order_fiscal_year = 2013
    GROUP BY
        d.order_fiscal_month_year,
        d.order_fiscal_year,
        d.order_fiscal_month
),
cohort_with_date AS
(
    SELECT
        c.customer_key,
        d.order_fiscal_month_year AS cohort_period,
        d.order_fiscal_year,
        d.order_fiscal_month
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
),
cohort_activity AS
(
    SELECT DISTINCT
        c.customer_key,
        c.cohort_period,
        c.order_fiscal_year AS cohort_year,
        c.order_fiscal_month AS cohort_month,

        d.order_fiscal_year AS activity_year,
        d.order_fiscal_month AS activity_month,

        (d.order_fiscal_year - c.order_fiscal_year) * 12 +
        (d.order_fiscal_month - c.order_fiscal_month) AS month_offset
    FROM cohort_with_date c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
    WHERE c.order_fiscal_year = 2013
)
SELECT
    a.cohort_period,
    b.total_customers,

    CAST(COUNT(DISTINCT CASE WHEN month_offset = 0 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R0,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 1 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R1,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 2 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R2,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 3 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R3,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 4 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R4,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 5 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R5,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 6 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R6,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 7 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R7,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 8 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R8,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 9 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R9,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 10 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R10,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 11 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R11

FROM cohort_activity a
JOIN cohort_base b
    ON a.cohort_period = b.cohort_period

GROUP BY
    a.cohort_period,
    b.total_customers

ORDER BY MIN(a.cohort_month);

/*
cohort_period	total_customers    	R0	    R1	    R2    	R3	    R4	    R5	    R6	    R7	    R8	    R9	    R10	    R11
Jan-2013      	249	                1.00	0.04	0.03	0.05	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.05
Feb-2013      	1091	            1.00	0.06	0.05	0.05	0.06	0.05	0.04	0.05	0.06	0.05	0.06	0.05
Mar-2013       	1302	            1.00	0.03	0.03	0.03	0.04	0.03	0.04	0.03	0.04	0.04	0.03	0.00
Apr-2013  	    1017	            1.00	0.03	0.04	0.03	0.03	0.04	0.03	0.02	0.03	0.03	0.00	0.00
May-2013  	    1015	            1.00	0.04	0.02	0.03	0.03	0.02	0.03	0.03	0.03	0.00	0.00	0.00
Jun-2013  	    1342	            1.00	0.02	0.03	0.04	0.03	0.03	0.03	0.02	0.00	0.00	0.00	0.00
Jul-2013  	    951	                1.00	0.02	0.03	0.03	0.03	0.04	0.02	0.00	0.00	0.00	0.00	0.00
Aug-2013  	    970	                1.00	0.02	0.03	0.02	0.03	0.02	0.00	0.00	0.00	0.00	0.00	0.00
Sep-2013  	    1209            	1.00	0.02	0.02	0.03	0.03	0.00	0.00	0.00	0.00	0.00	0.00	0.00
Oct-2013  	    1012	            1.00	0.02	0.02	0.02	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
Nov-2013  	    1063	            1.00	0.02	0.02	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
Dec-2013  	    1285	            1.00	0.02	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
*/
WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(d.order_date) AS first_order_date
    FROM gold.fact_sales f
    JOIN gold.dim_order_date d
        ON f.order_date_key = d.order_date_key
    GROUP BY f.customer_key
),
customer_activity AS
(
    SELECT DISTINCT
        c.customer_key,
        c.first_order_date,
        d.order_date AS activity_date,

        FLOOR(DATEDIFF(DAY, c.first_order_date, d.order_date) / 365.0) AS year_offset

    FROM customer_cohort c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
),
pivot_activity AS
(
    SELECT
        customer_key,
        MIN(first_order_date) AS first_order_date,

        MAX(CASE WHEN year_offset = 0 THEN 1 ELSE 0 END) AS Y0,
        MAX(CASE WHEN year_offset = 1 THEN 1 ELSE 0 END) AS Y1,
        MAX(CASE WHEN year_offset = 2 THEN 1 ELSE 0 END) AS Y2,
        MAX(CASE WHEN year_offset = 3 THEN 1 ELSE 0 END) AS Y3,
        MAX(CASE WHEN year_offset = 4 THEN 1 ELSE 0 END) AS Y4

    FROM customer_activity
    GROUP BY customer_key
),
cohort_size AS
(
    SELECT
        YEAR(first_order_date) AS cohort_year,
        COUNT(*) AS total_customers
    FROM pivot_activity
    GROUP BY YEAR(first_order_date)
)
SELECT
    YEAR(p.first_order_date) AS cohort_year,
    c.total_customers,

    1.0 AS R0,

    CAST(SUM(CASE WHEN Y1 = 1 THEN 1 ELSE 0 END) * 1.0 / c.total_customers AS DECIMAL(5,2)) AS R1,

    CAST(SUM(CASE WHEN Y1 = 1 AND Y2 = 1 THEN 1 ELSE 0 END) * 1.0 / c.total_customers AS DECIMAL(5,2)) AS R2,

    CAST(SUM(CASE WHEN Y1 = 1 AND Y2 = 1 AND Y3 = 1 THEN 1 ELSE 0 END) * 1.0 / c.total_customers AS DECIMAL(5,2)) AS R3,

    CAST(SUM(CASE WHEN Y1 = 1 AND Y2 = 1 AND Y3 = 1 AND Y4 = 1 THEN 1 ELSE 0 END) * 1.0 / c.total_customers AS DECIMAL(5,2)) AS R4

FROM pivot_activity p
JOIN cohort_size c
    ON YEAR(p.first_order_date) = c.cohort_year

GROUP BY
    YEAR(p.first_order_date),
    c.total_customers

ORDER BY cohort_year;
/*
cohort_year	total_customers	        R0        	R1	    R2	    R3    	R4
2010	    14	                    1.0	        0.00	0.00	0.00	0.00
2011	    2216	                1.0	        0.52	0.08	0.00	0.00
2012	    3225	                1.0	        0.52	0.00	0.00	0.00
2013	    12521	                1.0	        0.00	0.00	0.00	0.00
2014	    506	                    1.0	        0.00	0.00	0.00	0.00
*/
