-- =========================================================
-- COHORT ANALYSIS: CUSTOMER BEHAVIOR & REVENUE TRENDS
-- =========================================================

-- Definition:
-- A cohort is a group of customers who share a common
-- characteristic — here, their FIRST purchase date.

-- Cohort Type:
-- Acquisition Cohort (based on first purchase)

-- Granularity:
-- 1. Yearly (macro trend analysis)
-- 2. Monthly (detailed behavioral analysis)

-- Key Objective:
-- Track how customer value evolves over time after acquisition.

-- =========================================================
-- WHY COHORT ANALYSIS?
-- =========================================================

-- 1. Identifies retention patterns over time
-- 2. Separates growth from customer acquisition vs engagement
-- 3. Removes noise from aggregate metrics
-- 4. Enables lifecycle-based decision making
-- 5. Helps evaluate marketing effectiveness by cohort


WITH customer_cohort AS
(
    SELECT
        customer_key,
        MIN(order_date_key) AS first_order_date_key
    FROM gold.fact_sales
    GROUP BY customer_key
)

SELECT
    d.order_fiscal_year AS cohort_fiscal_year,
    COUNT(*) AS total_customers
FROM customer_cohort c
JOIN gold.dim_order_date d
    ON c.first_order_date_key = d.order_date_key
GROUP BY
    d.order_fiscal_year
ORDER BY
    d.order_fiscal_year;

/*
cohort_fiscal_year	total_customers
NULL	            15
2011	            2199
2012	            3258
2013	            12506
2014	            506
*/
-- The null values are the results of invalid order dates in the source data.
-- =========================================================
-- STEP 3: COHORT REVENUE OVER TIME
-- =========================================================

-- Objective:
-- Track revenue generated by each cohort across years.

-- Key Concept:
-- year_offset = years since customer acquisition

-- Interpretation:
-- Y0 → Revenue in acquisition year
-- Y1 → Revenue 1 year after acquisition
-- ...

-- Use Case:
-- Evaluate long-term value and retention quality.

WITH customer_cohort AS
(
    SELECT
        customer_key,
        MIN(order_date_key) AS first_order_date_key
    FROM gold.fact_sales
    GROUP BY customer_key
), cohort_with_year AS
(
    SELECT
        c.customer_key,
        d.order_fiscal_year AS cohort_fiscal_year -- Fiscal year
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
), cohort_activity AS
(
    SELECT
        c.customer_key,
        c.cohort_fiscal_year,
        d.order_fiscal_year,
        (d.order_fiscal_year - c.cohort_fiscal_year) AS year_offset,
        s.sales_amount
    FROM cohort_with_year c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
)SELECT
    cohort_fiscal_year,

    SUM(CASE WHEN year_offset = 0 THEN sales_amount ELSE 0 END) AS Y0,
    SUM(CASE WHEN year_offset = 1 THEN sales_amount ELSE 0 END) AS Y1,
    SUM(CASE WHEN year_offset = 2 THEN sales_amount ELSE 0 END) AS Y2,
    SUM(CASE WHEN year_offset = 3 THEN sales_amount ELSE 0 END) AS Y3,
    SUM(CASE WHEN year_offset = 4 THEN sales_amount ELSE 0 END) AS Y4

FROM cohort_activity
WHERE cohort_fiscal_year IS NOT NULL
GROUP BY cohort_fiscal_year
ORDER BY cohort_fiscal_year;
    
/*
cohort_fiscal_year	    Y0	        Y1	        Y2	        Y3	    Y4
2011	                7049833    	72811	    4281626    	0	    0
2012	                5861792	    6149063    	0	        0	    0
2013	                5876309	    19396	    0	        0	    0
2014	                26049	    0	        0	        0	    0
*/

--_____________________________________________________________________YEAR 2013 - comparing customers according to the month they arrived_________________________________
-- =========================================================
-- STEP 4: MONTHLY COHORT ANALYSIS (YEAR = 2013)
-- =========================================================

-- Objective:
-- Break down cohorts by acquisition month for granular insights.

-- Output:
-- Number of customers acquired each month in 2013

-- Use Case:
-- Detect seasonality in acquisition (e.g., campaigns, holidays)
WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(f.order_date_key) AS first_order_date_key
    FROM gold.fact_sales f
    GROUP BY f.customer_key
)

SELECT
    d.order_fiscal_month_year AS cohort_period,
    COUNT(DISTINCT c.customer_key) AS total_customers
FROM customer_cohort c
JOIN gold.dim_order_date d
    ON c.first_order_date_key = d.order_date_key
WHERE d.order_fiscal_year = 2013
GROUP BY
    d.order_fiscal_month_year
ORDER BY
    d.order_fiscal_month_year;
/*
cohort_period	total_customers
Apr-2013      	1017
Aug-2013      	970
Dec-2013      	1285
Feb-2013      	1091
Jan-2013      	249
Jul-2013      	951
Jun-2013  	    1342
Mar-2013  	    1302
May-2013  	    1015
Nov-2013  	    1063
Oct-2013  	    1012
Sep-2013  	    1209
*/
-- =========================================================
-- STEP 4: MONTHLY COHORT ANALYSIS (YEAR = 2013)
-- =========================================================

-- Objective:
-- Break down cohorts by acquisition month for granular insights.

-- Output:
-- Number of customers acquired each month in 2013

-- Use Case:
-- Detect seasonality in acquisition (e.g., campaigns, holidays)
WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(f.order_date_key) AS first_order_date_key
    FROM gold.fact_sales f
    GROUP BY f.customer_key
)
, cohort_with_date AS
(
    SELECT
        c.customer_key,
        d.order_fiscal_year,
        d.order_fiscal_month,
        d.order_fiscal_month_year AS cohort_period,
        c.first_order_date_key
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
)
, cohort_activity AS
(
    SELECT
        c.customer_key,
        c.cohort_period,
        c.order_fiscal_year AS cohort_year,
        c.order_fiscal_month AS cohort_month,

        d.order_fiscal_year AS activity_year,
        d.order_fiscal_month AS activity_month,

        (d.order_fiscal_year - c.order_fiscal_year) * 12 +
        (d.order_fiscal_month - c.order_fiscal_month) AS month_offset,

        s.sales_amount
    FROM cohort_with_date c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
    WHERE c.order_fiscal_year = 2013
)
SELECT
    cohort_period,

    SUM(CASE WHEN month_offset = 0 THEN sales_amount ELSE 0 END) AS M0,
    SUM(CASE WHEN month_offset = 1 THEN sales_amount ELSE 0 END) AS M1,
    SUM(CASE WHEN month_offset = 2 THEN sales_amount ELSE 0 END) AS M2,
    SUM(CASE WHEN month_offset = 3 THEN sales_amount ELSE 0 END) AS M3,
    SUM(CASE WHEN month_offset = 4 THEN sales_amount ELSE 0 END) AS M4,
    SUM(CASE WHEN month_offset = 5 THEN sales_amount ELSE 0 END) AS M5,
    SUM(CASE WHEN month_offset = 6 THEN sales_amount ELSE 0 END) AS M6,
    SUM(CASE WHEN month_offset = 7 THEN sales_amount ELSE 0 END) AS M7,
    SUM(CASE WHEN month_offset = 8 THEN sales_amount ELSE 0 END) AS M8,
    SUM(CASE WHEN month_offset = 9 THEN sales_amount ELSE 0 END) AS M9,
    SUM(CASE WHEN month_offset = 10 THEN sales_amount ELSE 0 END) AS M10,
    SUM(CASE WHEN month_offset = 11 THEN sales_amount ELSE 0 END) AS M11

FROM cohort_activity
GROUP BY cohort_period
ORDER BY MIN(cohort_month);

/*
cohort_period	    M0	        M1	        M2	        M3	        M4	        M5	        M6	        M7	        M8        	M9	           M10        	M11
Jan-2013  	        295407	    810	        498	        5489	    3123	    801	        1056    	5488    	394	        1547	       4506        	2216
Feb-2013  	        295175	    4679    	4169	    8522	    11173	    4480    	2854	    4475	    3941	    4050	       4905        	3413
Mar-2013  	        388986	    2185	    2769	    9847	    12035	    11357	    3059	    2413	    2660	    2681	       2221        	0
Apr-2013  	        375364	    1508	    5245	    8581	    1477	    4843	    1530	    1151	    2061	    1659	       0	        0
May-2013  	        416393	    2267	    8473	    13204	    10999	    1189	    1490	    1740	    1885    	0	           0	        0
Jun-2013  	        617001	    1281	    4604	    7047	    27967	    7105	    2225	    1433	    0	        0	           0	        0
Jul-2013  	        325126	    724	        1676	    1488	    3669	    21337	    1462	    0	        0	        0	           0	        0
Aug-2013  	        341536	    1307	    2303	    1663	    14096	    1338	    0        	0	        0        	0	           0	        0
Sep-2013  	        479696	    2479	    1591	    2095	    1713	    0	        0	        0	        0        	0	           0	        0
Oct-2013  	        516918	    1416	    1419	    985	        0	        0        	0	        0	        0	        0	           0	        0
Nov-2013  	        692415    	1437	    1220	    0	        0	        0	        0	        0	        0	        0	           0	        0
Dec-2013  	        829423	    1523	    0	        0	        0	        0	        0	        0	        0	        0	           0	        0
*/
-- =========================================================
-- STEP 5: MONTHLY REVENUE RETENTION MATRIX
-- =========================================================

-- Objective:
-- Track how each monthly cohort spends over time.

-- Key Metric:
-- month_offset = months since first purchase

-- Interpretation:
-- M0 → Revenue in acquisition month
-- M1 → Revenue next month
-- ...

-- Insight:
-- Helps visualize retention decay and repeat purchase behavior.

WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(f.order_date_key) AS first_order_date_key
    FROM gold.fact_sales f
    GROUP BY f.customer_key
),
cohort_base AS
(
    SELECT
        d.order_fiscal_year,
        d.order_fiscal_month,
        d.order_fiscal_month_year AS cohort_period,
        COUNT(DISTINCT c.customer_key) AS total_customers
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
    WHERE d.order_fiscal_year = 2013
    GROUP BY
        d.order_fiscal_year,
        d.order_fiscal_month,
        d.order_fiscal_month_year
),
cohort_with_date AS
(
    SELECT
        c.customer_key,
        d.order_fiscal_year,
        d.order_fiscal_month,
        d.order_fiscal_month_year AS cohort_period,
        c.first_order_date_key
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
),
cohort_activity AS
(
    SELECT
        c.customer_key,
        c.cohort_period,
        c.order_fiscal_year AS cohort_year,
        c.order_fiscal_month AS cohort_month,
        d.order_fiscal_year AS activity_year,
        d.order_fiscal_month AS activity_month,
        (d.order_fiscal_year - c.order_fiscal_year) * 12 +
        (d.order_fiscal_month - c.order_fiscal_month) AS month_offset,
        s.sales_amount
    FROM cohort_with_date c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
    WHERE c.order_fiscal_year = 2013
)
SELECT
    a.cohort_period,
    b.total_customers,
    CAST(SUM(CASE WHEN month_offset = 0 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M0,
    CAST(SUM(CASE WHEN month_offset = 1 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M1,
    CAST(SUM(CASE WHEN month_offset = 2 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M2,
    CAST(SUM(CASE WHEN month_offset = 3 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M3,
    CAST(SUM(CASE WHEN month_offset = 4 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M4,
    CAST(SUM(CASE WHEN month_offset = 5 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M5,
    CAST(SUM(CASE WHEN month_offset = 6 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M6,
    CAST(SUM(CASE WHEN month_offset = 7 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M7,
    CAST(SUM(CASE WHEN month_offset = 8 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M8,
    CAST(SUM(CASE WHEN month_offset = 9 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M9,
    CAST(SUM(CASE WHEN month_offset = 10 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M10,
    CAST(SUM(CASE WHEN month_offset = 11 THEN sales_amount ELSE 0 END) * 1.0 / b.total_customers AS DECIMAL(10,2)) AS ARPU_M11
FROM cohort_activity a
JOIN cohort_base b
    ON a.cohort_period = b.cohort_period
GROUP BY
    a.cohort_period,
    b.total_customers
ORDER BY MIN(a.cohort_month); 

/*
cohort_period	total_customers    	ARPU_M0    	    ARPU_M1	    ARPU_M2    	ARPU_M3	    ARPU_M4	    ARPU_M5	    ARPU_M6	    ARPU_M7	    ARPU_M8    	ARPU_M9    	ARPU_M10	ARPU_M11
Jan-2013  	    249	                1186.37    	    3.25	    2.00	    22.04	    12.54	    3.22	    4.24	    22.04	    1.58	    6.21	    18.10	    8.90
Feb-2013  	    1091	            270.55	        4.29	    3.82	    7.81	    10.24	    4.11	    2.62	    4.10	    3.61	    3.71	    4.50	    3.13
Mar-2013  	    1302	            298.76	        1.68	    2.13	    7.56	    9.24	    8.72	    2.35	    1.85	    2.04	    2.06	    1.71	    0.00
Apr-2013  	    1017	            369.09	        1.48	    5.16	    8.44	    1.45	    4.76	    1.50	    1.13	    2.03	    1.63	    0.00	    0.00
May-2013  	    1015	            410.24	        2.23	    8.35	    13.01	    10.84	    1.17	    1.47	    1.71	    1.86	    0.00	    0.00	    0.00
Jun-2013  	    1342	            459.76        	0.95	    3.43	    5.25	    20.84	    5.29	    1.66	    1.07	    0.00	    0.00	    0.00	    0.00
Jul-2013  	    951	                341.88        	0.76	    1.76	    1.56	    3.86	    22.44	    1.54	    0.00	    0.00	    0.00	    0.00	    0.00
Aug-2013  	    970	                352.10	        1.35    	2.37       	1.71	    14.53	    1.38	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00
Sep-2013  	    1209	            396.77	        2.05    	1.32	    1.73	    1.42	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00
Oct-2013  	    1012	            510.79	        1.40    	1.40	    0.97	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00
Nov-2013  	    1063	            651.38        	1.35    	1.15	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00	    0.00
Dec-2013  	    1285	            645.47        	1.19	    0.00	    0.00	    0.00	    0.00    	0.00	    0.00	    0.00	    0.00	    0.00	    0.00
*/

WITH customer_cohort AS
(
    SELECT
        f.customer_key,
        MIN(f.order_date_key) AS first_order_date_key
    FROM gold.fact_sales f
    GROUP BY f.customer_key
),
cohort_base AS
(
    SELECT
        d.order_fiscal_month_year AS cohort_period,
        d.order_fiscal_year,
        d.order_fiscal_month,
        COUNT(DISTINCT c.customer_key) AS total_customers
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
    WHERE d.order_fiscal_year = 2013
    GROUP BY
        d.order_fiscal_month_year,
        d.order_fiscal_year,
        d.order_fiscal_month
),
cohort_with_date AS
(
    SELECT
        c.customer_key,
        d.order_fiscal_month_year AS cohort_period,
        d.order_fiscal_year,
        d.order_fiscal_month
    FROM customer_cohort c
    JOIN gold.dim_order_date d
        ON c.first_order_date_key = d.order_date_key
),
cohort_activity AS
(
    SELECT DISTINCT
        c.customer_key,
        c.cohort_period,
        c.order_fiscal_year AS cohort_year,
        c.order_fiscal_month AS cohort_month,

        d.order_fiscal_year AS activity_year,
        d.order_fiscal_month AS activity_month,

        (d.order_fiscal_year - c.order_fiscal_year) * 12 +
        (d.order_fiscal_month - c.order_fiscal_month) AS month_offset
    FROM cohort_with_date c
    JOIN gold.fact_sales s
        ON c.customer_key = s.customer_key
    JOIN gold.dim_order_date d
        ON s.order_date_key = d.order_date_key
    WHERE c.order_fiscal_year = 2013
)
SELECT
    a.cohort_period,
    b.total_customers,

    CAST(COUNT(DISTINCT CASE WHEN month_offset = 0 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R0,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 1 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R1,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 2 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R2,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 3 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R3,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 4 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R4,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 5 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R5,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 6 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R6,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 7 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R7,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 8 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R8,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 9 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R9,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 10 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R10,
    CAST(COUNT(DISTINCT CASE WHEN month_offset = 11 THEN a.customer_key END) * 1.0 / b.total_customers AS DECIMAL(5,2)) AS R11

FROM cohort_activity a
JOIN cohort_base b
    ON a.cohort_period = b.cohort_period

GROUP BY
    a.cohort_period,
    b.total_customers

ORDER BY MIN(a.cohort_month);

/*
cohort_period	total_customers    	R0	    R1	    R2    	R3	    R4	    R5	    R6	    R7	    R8	    R9	    R10	    R11
Jan-2013      	249	                1.00	0.04	0.03	0.05	0.04	0.04	0.04	0.04	0.04	0.04	0.04	0.05
Feb-2013      	1091	            1.00	0.06	0.05	0.05	0.06	0.05	0.04	0.05	0.06	0.05	0.06	0.05
Mar-2013       	1302	            1.00	0.03	0.03	0.03	0.04	0.03	0.04	0.03	0.04	0.04	0.03	0.00
Apr-2013  	    1017	            1.00	0.03	0.04	0.03	0.03	0.04	0.03	0.02	0.03	0.03	0.00	0.00
May-2013  	    1015	            1.00	0.04	0.02	0.03	0.03	0.02	0.03	0.03	0.03	0.00	0.00	0.00
Jun-2013  	    1342	            1.00	0.02	0.03	0.04	0.03	0.03	0.03	0.02	0.00	0.00	0.00	0.00
Jul-2013  	    951	                1.00	0.02	0.03	0.03	0.03	0.04	0.02	0.00	0.00	0.00	0.00	0.00
Aug-2013  	    970	                1.00	0.02	0.03	0.02	0.03	0.02	0.00	0.00	0.00	0.00	0.00	0.00
Sep-2013  	    1209            	1.00	0.02	0.02	0.03	0.03	0.00	0.00	0.00	0.00	0.00	0.00	0.00
Oct-2013  	    1012	            1.00	0.02	0.02	0.02	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
Nov-2013  	    1063	            1.00	0.02	0.02	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
Dec-2013  	    1285	            1.00	0.02	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00	0.00
*/
